#!/usr/bin/env bash
#
# First-time provisioning for the DonutSMP Transaction Tracker on a Debian or
# Ubuntu VPS. Run as root, with the repository already copied to REMOTE_DIR
# (deploy/vps.sh push does that for you).
#
# Usage:
#   bash vps-setup.sh <hostname> <use_tls 0|1> <letsencrypt_email> \
#                     <db_name> <db_user> <remote_dir> [frontend_port]
#
# frontend_port defaults to 18701 and is only used when TLS is off: the SPA
# then lives at http://<host>:<port>/ on its own unique port instead of
# claiming port 80. With TLS on, nginx listens on 80/443 for the domain and the
# port is ignored.
#
# Idempotent: safe to re-run. It never overwrites an existing backend/.env, so
# your API key and database password survive upgrades. Use deploy/vps.sh update
# for routine redeploys.

set -euo pipefail

HOSTNAME_ARG="${1:-_}"
USE_TLS="${2:-0}"
LE_EMAIL="${3:-}"
DB_NAME="${4:-donutsmp}"
DB_USER="${5:-donut}"
REMOTE_DIR="${6:-/opt/donutsmp-tracker}"
FRONTEND_PORT="${7:-18701}"
APP_USER="donut"
SVC_NAME="donutsmp-api"
VENV="$REMOTE_DIR/backend/.venv"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m[warn] %s\033[0m\n' "$*"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root." >&2
    exit 1
fi

if [ ! -d "$REMOTE_DIR/backend/app" ]; then
    echo "Expected the repository at $REMOTE_DIR (missing backend/app)." >&2
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------- packages
log "Installing system packages"
apt-get update -qq
apt-get install -y -qq \
    python3 python3-venv python3-pip \
    postgresql postgresql-contrib \
    nginx rsync curl ca-certificates

if [ "$USE_TLS" = "1" ]; then
    apt-get install -y -qq certbot python3-certbot-nginx
fi

# ---------------------------------------------------------------- app user
if ! id -u "$APP_USER" >/dev/null 2>&1; then
    log "Creating system user $APP_USER"
    useradd --system --home-dir "$REMOTE_DIR" --shell /usr/sbin/nologin "$APP_USER"
fi

# ---------------------------------------------------------------- postgres
log "Configuring PostgreSQL database $DB_NAME"
systemctl enable --now postgresql >/dev/null 2>&1 || true

run_psql() { sudo -u postgres psql -v ON_ERROR_STOP=1 -tAc "$1"; }

DB_PASSWORD=""
if [ -f "$REMOTE_DIR/backend/.env" ] && grep -q '^DATABASE_URL=' "$REMOTE_DIR/backend/.env"; then
    # Reuse the password already embedded in the existing DATABASE_URL.
    DB_PASSWORD="$(grep '^DATABASE_URL=' "$REMOTE_DIR/backend/.env" \
        | sed -n 's|.*://[^:]*:\([^@]*\)@.*|\1|p')"
    DB_PASSWORD="$(printf '%b' "${DB_PASSWORD//%/\\x}")"
fi
if [ -z "$DB_PASSWORD" ]; then
    DB_PASSWORD="$(openssl rand -hex 24)"
fi

if [ "$(run_psql "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'")" != "1" ]; then
    run_psql "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD'"
else
    run_psql "ALTER ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASSWORD'"
fi

if [ "$(run_psql "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'")" != "1" ]; then
    run_psql "CREATE DATABASE $DB_NAME OWNER $DB_USER"
fi
run_psql "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER"
# Postgres 15+ removed the implicit CREATE on the public schema.
sudo -u postgres psql -d "$DB_NAME" -v ON_ERROR_STOP=1 -q \
    -c "GRANT ALL ON SCHEMA public TO $DB_USER" \
    -c "ALTER SCHEMA public OWNER TO $DB_USER" >/dev/null

# ---------------------------------------------------------------- .env
ENV_FILE="$REMOTE_DIR/backend/.env"
if [ -f "$ENV_FILE" ]; then
    log "Keeping existing $ENV_FILE"
else
    log "Writing $ENV_FILE"
    API_KEY="$(openssl rand -base64 36 | tr -d '\n=+/' | cut -c1-40)"
    cat > "$ENV_FILE" <<EOF
# Generated by deploy/vps-setup.sh. Keep this file private: it holds the API key
# that the Minecraft mod uses to upload observations.
DATABASE_URL=postgresql+asyncpg://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME
API_KEY=$API_KEY
HOST=127.0.0.1
PORT=18700
DASHBOARD_PORT=18701
FRONTEND_DIST=$REMOTE_DIR/frontend/dist
AUTO_CREATE_TABLES=0
# Same-origin hosting means CORS is not needed for the dashboard; these are for
# local development against the same database.
CORS_ORIGINS=http://localhost:18701,http://127.0.0.1:15173
SESSION_TTL_DAYS=7
LINK_CODE_TTL_SECONDS=300
SESSION_COOKIE_NAME=dtt_session
# Auto-enabled when the request arrives over https, so this stays false even
# behind a TLS terminator.
COOKIE_SECURE=false
EOF
    chmod 600 "$ENV_FILE"
fi

# ---------------------------------------------------------------- venv
log "Installing Python dependencies into $VENV"
if [ ! -x "$VENV/bin/python" ]; then
    python3 -m venv "$VENV"
fi
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$REMOTE_DIR/backend/requirements.txt"

# ---------------------------------------------------------------- database schema
log "Applying database migrations"
(cd "$REMOTE_DIR/backend" && "$VENV/bin/python" -m alembic upgrade head)

log "Fixing ownership of $REMOTE_DIR"
chown -R "$APP_USER:$APP_USER" "$REMOTE_DIR"

# ---------------------------------------------------------------- systemd
log "Installing $SVC_NAME.service"
install -m 644 "$REMOTE_DIR/deploy/systemd/$SVC_NAME.service" \
    "/etc/systemd/system/$SVC_NAME.service"
systemctl daemon-reload
systemctl enable "$SVC_NAME" >/dev/null 2>&1 || true
systemctl restart "$SVC_NAME"

# ---------------------------------------------------------------- nginx
log "Installing shared security headers snippet"
mkdir -p /etc/nginx/snippets
install -m 644 "$REMOTE_DIR/deploy/nginx/security-headers.conf" \
    /etc/nginx/snippets/donutsmp-security.conf

log "Installing nginx site"
if [ "$USE_TLS" = "1" ]; then
    # A TLS server block points at certificate files that do not exist yet, and
    # nginx refuses to load a config with a missing certificate. So serve plain
    # HTTP on port 80 first, obtain the certificate, then swap in the TLS block.
    SRC_HTTP="$REMOTE_DIR/deploy/nginx/donutsmp-http.conf"
    sed -i "s/__SERVER_NAME__/$HOSTNAME_ARG/g" "$SRC_HTTP"
    install -m 644 "$SRC_HTTP" /etc/nginx/sites-available/donutsmp.conf
    ln -sf /etc/nginx/sites-available/donutsmp.conf /etc/nginx/sites-enabled/donutsmp.conf

    if ! nginx -t 2>/tmp/nginx-test.err; then
        cat /tmp/nginx-test.err >&2
        rm -f /etc/nginx/sites-enabled/donutsmp.conf
        echo "nginx config test failed (pre-TLS bootstrap); removed the new site." >&2
        exit 1
    fi
    systemctl enable nginx >/dev/null 2>&1 || true
    systemctl reload nginx 2>/dev/null || systemctl restart nginx

    if [ ! -f "/etc/letsencrypt/live/$HOSTNAME_ARG/fullchain.pem" ]; then
        log "Requesting Let's Encrypt certificate for $HOSTNAME_ARG"
        CERTBOT_ARGS=(certonly --nginx -d "$HOSTNAME_ARG" --non-interactive --agree-tos)
        if [ -n "$LE_EMAIL" ]; then
            CERTBOT_ARGS+=(-m "$LE_EMAIL")
        else
            CERTBOT_ARGS+=(--register-unsafely-without-email)
        fi
        if ! certbot "${CERTBOT_ARGS[@]}"; then
            warn "certbot failed; leaving the site on plain HTTP"
            exit 0
        fi
    fi

    SRC="$REMOTE_DIR/deploy/nginx/donutsmp.conf"
    sed -i "s/tracker\.example\.com/$HOSTNAME_ARG/g" "$SRC"
elif [ "$FRONTEND_PORT" != "80" ]; then
    # Own high port, so this never competes for port 80 with a live site.
    SRC="$REMOTE_DIR/deploy/nginx/donutsmp-port.conf"
    sed -i "s/__SERVER_NAME__/$HOSTNAME_ARG/g; s/__FRONTEND_PORT__/$FRONTEND_PORT/g" "$SRC"
else
    SRC="$REMOTE_DIR/deploy/nginx/donutsmp-http.conf"
    # Match the exact IP so we never fight another site for the port-80
    # catch-all on a shared server.
    sed -i "s/__SERVER_NAME__/$HOSTNAME_ARG/g" "$SRC"
fi
install -m 644 "$SRC" /etc/nginx/sites-available/donutsmp.conf
ln -sf /etc/nginx/sites-available/donutsmp.conf /etc/nginx/sites-enabled/donutsmp.conf

if ! nginx -t 2>/tmp/nginx-test.err; then
    cat /tmp/nginx-test.err >&2
    rm -f /etc/nginx/sites-enabled/donutsmp.conf
    echo "nginx config test failed; removed the new site and left nginx untouched." >&2
    exit 1
fi
systemctl enable nginx >/dev/null 2>&1 || true
systemctl reload nginx 2>/dev/null || systemctl restart nginx

# ---------------------------------------------------------------- firewall
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
    if [ "$USE_TLS" = "1" ]; then
        log "Opening firewall for 80/443"
        ufw allow 80/tcp >/dev/null 2>&1 || true
        ufw allow 443/tcp >/dev/null 2>&1 || true
    elif [ "$FRONTEND_PORT" != "80" ]; then
        log "Opening firewall for $FRONTEND_PORT"
        ufw allow "$FRONTEND_PORT"/tcp >/dev/null 2>&1 || true
    else
        log "Opening firewall for 80"
        ufw allow 80/tcp >/dev/null 2>&1 || true
    fi
fi

# ---------------------------------------------------------------- summary
API_KEY_VALUE="$(grep '^API_KEY=' "$ENV_FILE" | cut -d= -f2-)"
log "Done"
if [ "$USE_TLS" = "1" ]; then
    DASH_URL="https://$HOSTNAME_ARG"
    API_URL="https://$HOSTNAME_ARG/api/health"
else
    DASH_URL="http://$HOSTNAME_ARG:$FRONTEND_PORT"
    API_URL="http://$HOSTNAME_ARG:$FRONTEND_PORT/api/health"
fi
cat <<EOF

Dashboard : $DASH_URL
API       : $API_URL
Service   : systemctl status $SVC_NAME
Logs      : journalctl -u $SVC_NAME -f

Point the Minecraft mod at this server (config JSON):
  "backendUrl": "$DASH_URL",
  "apiKey": "$API_KEY_VALUE"

EOF
