"""initial schema

Revision ID: e9a5293d1f44
Revises: 
Create Date: 2026-09-15 17:17:50.271708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a5293d1f44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=32), nullable=False),
    sa.Column('seller_username', sa.String(length=32), nullable=True),
    sa.Column('buyer_username', sa.String(length=32), nullable=True),
    sa.Column('item_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('fulfilled_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_username'), 'orders', ['buyer_username'], unique=False)
    op.create_index(op.f('ix_orders_item_name'), 'orders', ['item_name'], unique=False)
    op.create_index(op.f('ix_orders_owner_username'), 'orders', ['owner_username'], unique=False)
    op.create_index(op.f('ix_orders_seller_username'), 'orders', ['seller_username'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_address'), 'servers', ['address'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('server_address', sa.String(length=128), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('transaction_owner', sa.String(length=32), nullable=False),
    sa.Column('observed_by', sa.String(length=32), nullable=False),
    sa.Column('buyer_username', sa.String(length=32), nullable=True),
    sa.Column('seller_username', sa.String(length=32), nullable=True),
    sa.Column('recipient_username', sa.String(length=32), nullable=True),
    sa.Column('item_name', sa.String(length=128), nullable=True),
    sa.Column('item_id', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('money_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('money_received', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('normalized_message', sa.Text(), nullable=False),
    sa.Column('parsed_successfully', sa.Boolean(), nullable=False),
    sa.Column('minecraft_timestamp', sa.String(length=16), nullable=True),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_buyer_username'), 'transactions', ['buyer_username'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_transactions_item_name'), 'transactions', ['item_name'], unique=False)
    op.create_index(op.f('ix_transactions_observed_by'), 'transactions', ['observed_by'], unique=False)
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_username'), 'transactions', ['recipient_username'], unique=False)
    op.create_index(op.f('ix_transactions_seller_username'), 'transactions', ['seller_username'], unique=False)
    op.create_index(op.f('ix_transactions_server'), 'transactions', ['server'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_owner'), 'transactions', ['transaction_owner'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index('ix_tx_item_time', 'transactions', ['item_name', 'created_at'], unique=False)
    op.create_index('ix_tx_owner_type_time', 'transactions', ['transaction_owner', 'transaction_type', 'created_at'], unique=False)
    op.create_table('transaction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('player', sa.String(length=32), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_events_order_id'), 'transaction_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_transaction_events_transaction_id'), 'transaction_events', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_events_transaction_id'), table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_order_id'), table_name='transaction_events')
    op.drop_table('transaction_events')
    op.drop_index('ix_tx_owner_type_time', table_name='transactions')
    op.drop_index('ix_tx_item_time', table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_owner'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_server'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_seller_username'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_username'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_observed_by'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_buyer_username'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_servers_address'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_seller_username'), table_name='orders')
    op.drop_index(op.f('ix_orders_owner_username'), table_name='orders')
    op.drop_index(op.f('ix_orders_item_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_username'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
